#!/bin/bash
# To use, add this to /etc/rc.local:
# su -c "/home/odroid/jarvis/arm/scripts/autorecord" -s /bin/bash odroid | tee -a /home/odroid/.autorecord.log

mkdir -p /home/odroid/autorecord

if [ -n "`lsusb | grep ASUS`" ]; then
    echo `date`   ASUS found - starting autorecord 
    cd /home/odroid/autorecord
    source /opt/ros/fuerte/setup.bash
    export ROS_PACKAGE_PATH=/home/odroid/jarvis/ros-pkg/core:/home/odroid/jarvis/ros-pkg:/opt/ros/fuerte/share:/opt/ros/fuerte/stacks # core pkgs take priority over others.
    roslaunch sentinel record_bags.launch >> /home/odroid/autorecord/roslog.txt 2>&1 &
else
    echo `date`   No ASUS found - not starting autorecord 
fi
    
