
############################################################
# -- Global settings.
############################################################

REPO_ROOT		:= /earth/jarvis.git  # Change me.
# You'll need a symlink in your project dir to the data.
# This dir has subdirectories of configuration0, configuration1, etc.
DATA_DIR		:= $(MAKE_ROOT)/data  

SHELL			:= /bin/bash
MAKE_ROOT		:= $(REPO_ROOT)/src/project/calibration
MAKEFILE		:= $(MAKE_ROOT)/Makefile
export NUM_THREADS	:= 8
export ROS_PACKAGE_PATH	:=$(ROS_PACKAGE_PATH):$(REPO_ROOT)/src/ros-pkg

.SECONDEXPANSION:	# Allows use of automatic vars in prerequisites.
.SECONDARY:		# Prevents deletion of intermediate targets in a chain of implicit rules.

all:
	@echo You should probably be more specific.


############################################################
# -- Experiments
############################################################


############################################################
# -- Plots
############################################################


############################################################
# -- Latex
############################################################

