GlobalParams:
  NumCells: 10
  ObjThresh: 50
Pipeline:
  Pods:
    - Name: BlobEntryPoint
      Type: EntryPoint<Blob::Ptr>
      Params: ~
      Inputs: ~
    - Name: BlobProjector
      Type: BlobProjector
      Params: ~
      Inputs:
        Blob: BlobEntryPoint.Output
    - Name: GravitationalCloudOrienter
      Type: GravitationalCloudOrienter
      Params: ~
      Inputs:
        ProjectedBlob: BlobProjector.ProjectedBlob
    - Name: TrajectoryAccumulator
      Type: TrajectoryAccumulator
      Params: ~
      Inputs:
        UppedCloud: GravitationalCloudOrienter.UppedCloud
    - Name: TrajectoryStatistics01
      Type: TrajectoryStatistics
      Params:
        Lookback: 1
      Inputs:
        Trajectory: TrajectoryAccumulator.Trajectory
    - Name: TrajectoryStatistics10
      Type: TrajectoryStatistics
      Params:
        Lookback: 10
      Inputs:
        Trajectory: TrajectoryAccumulator.Trajectory
    - Name: CloudOrienter
      Type: CloudOrienter
      Params:
        OrientCloud: False
      Inputs:
        ProjectedBlob: BlobProjector.ProjectedBlob
    - Name: OrientedBoundingBoxSize
      Type: BoundingBoxSize
      Params: ~
      Inputs:
        Cloud: GravitationalCloudOrienter.OrientedCloud
    - Name: OrientedNormalizedDensityHistogram
      Type: NormalizedDensityHistogram
      Params:
        NumBins: 10
      Inputs:
        Cloud: GravitationalCloudOrienter.OrientedCloud
    - Name: CloudProjectorXY
      Type: CloudProjector
      Params:
        View: XY
        PixelsPerMeter: 50
        NumRows: 50
        NumCols: 50
        MinIntensity: 1
        KernelSize: 1
      Inputs:
        Cloud: GravitationalCloudOrienter.OrientedCloud
    - Name: CloudProjectorYZ
      Type: CloudProjector
      Params:
        View: YZ
        PixelsPerMeter: 50
        NumRows: 50
        NumCols: 50
        MinIntensity: 1
        KernelSize: 1
      Inputs:
        Cloud: GravitationalCloudOrienter.OrientedCloud
    - Name: CloudProjectorXZ
      Type: CloudProjector
      Params:
        View: XZ
        PixelsPerMeter: 50
        NumRows: 50
        NumCols: 50
        MinIntensity: 1
        KernelSize: 1
      Inputs:
        Cloud: GravitationalCloudOrienter.OrientedCloud
    - Name: DynamicImageWindowXY
      Type: DynamicImageWindow
      Params:
        VerticalAlignment: Center
        HorizontalAlignment: Center
        HeightPercent: 1
        WidthPercent: 1
        Scaling: 1
      Inputs:
        Image: CloudProjectorXY.Image
    - Name: HogArrayXY
      Type: HogArray
      Params:
        WindowWidth: 25
        WindowHeight: 25
        BlockWidth: 25
        BlockHeight: 25
        BlockStride: 25
        CellSize: 5
        NumBins: 6
        UVPattern: Dense
      Inputs:
        Image: DynamicImageWindowXY.Image
    - Name: DynamicImageWindowYZ
      Type: DynamicImageWindow
      Params:
        VerticalAlignment: Center
        HorizontalAlignment: Center
        HeightPercent: 1
        WidthPercent: 1
        Scaling: 1
      Inputs:
        Image: CloudProjectorYZ.Image
    - Name: HogArrayYZ
      Type: HogArray
      Params:
        WindowWidth: 25
        WindowHeight: 25
        BlockWidth: 25
        BlockHeight: 25
        BlockStride: 25
        CellSize: 5
        NumBins: 6
        UVPattern: Dense
      Inputs:
        Image: DynamicImageWindowYZ.Image
    - Name: DynamicImageWindowXZ
      Type: DynamicImageWindow
      Params:
        VerticalAlignment: Center
        HorizontalAlignment: Center
        HeightPercent: 1
        WidthPercent: 1
        Scaling: 1
      Inputs:
        Image: CloudProjectorXZ.Image
    - Name: HogArrayXZ
      Type: HogArray
      Params:
        WindowWidth: 25
        WindowHeight: 25
        BlockWidth: 25
        BlockHeight: 25
        BlockStride: 25
        CellSize: 5
        NumBins: 6
        UVPattern: Dense
      Inputs:
        Image: DynamicImageWindowXZ.Image
    - Name: HSVHistogram
      Type: HSVHistogram
      Params:
        NumBins: 10
        ValueThreshold: 0.2
        SaturationThreshold: 0.2
      Inputs:
        Blob: BlobProjector.ProjectedBlob  # Can't use the EntryPoint because of const-correctness.
    - Name: DescriptorAggregator
      Type: DescriptorAggregator
      Params: ~
      Inputs:
        Descriptors: >
          OrientedBoundingBoxSize.BoundingBoxSize
          OrientedNormalizedDensityHistogram.X
          OrientedNormalizedDensityHistogram.Y
          OrientedNormalizedDensityHistogram.Z
          HogArrayXY.ConcatenatedDescriptors
          HogArrayYZ.ConcatenatedDescriptors
          HogArrayXZ.ConcatenatedDescriptors
          HSVHistogram.Hue
          HSVHistogram.Saturation
          HSVHistogram.Value
          CloudOrienter.Eigenvalues
          CloudOrienter.RelativeCurvature
          TrajectoryStatistics01.MeanSpeed
          TrajectoryStatistics01.MeanVelocity
          TrajectoryStatistics01.MeanAngularSpeed
          TrajectoryStatistics10.MeanSpeed
          TrajectoryStatistics10.MeanVelocity
          TrajectoryStatistics10.MeanAngularSpeed
#          GravitationalCloudOrienter.Height
#          GravitationalCloudOrienter.HighestPoint
          
